# Generated by Django 2.1.4 on 2018-12-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('ca_id', models.CharField(db_column='CA_ID', max_length=100, primary_key=True, serialize=False)),
                ('ca_data', models.CharField(db_column='CA_DATA', max_length=150)),
                ('ca_datetime', models.DateTimeField(db_column='CA_DATETIME')),
                ('ca_desc', models.CharField(db_column='CA_DESC', max_length=500)),
                ('ca_head', models.CharField(db_column='CA_HEAD', max_length=300)),
            ],
            options={
                'db_table': 'announcement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('ct_id', models.AutoField(db_column='CT_ID', primary_key=True, serialize=False)),
                ('ct_name', models.CharField(db_column='CT_NAME', max_length=30)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('c_id', models.BigIntegerField(db_column='C_ID', primary_key=True, serialize=False)),
                ('c_acro', models.CharField(db_column='C_ACRO', max_length=50)),
                ('c_name', models.CharField(db_column='C_NAME', max_length=100)),
                ('c_isin', models.CharField(db_column='C_ISIN', max_length=30)),
                ('c_indus', models.CharField(db_column='C_INDUS', max_length=100)),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('su_id', models.AutoField(db_column='SU_ID', primary_key=True, serialize=False)),
                ('su_name', models.CharField(db_column='SU_NAME', max_length=50)),
            ],
            options={
                'db_table': 'subcategory',
                'managed': False,
            },
        ),
    ]
