# Generated by Django 2.1.4 on 2019-01-02 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'managed': False, 'ordering': ('-ca_data',)},
        ),
    ]
