# Generated by Django 2.1.4 on 2019-01-01 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_auto_20190102_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'managed': False, 'ordering': ('-ca_datetime',)},
        ),
    ]
