# Generated by Django 2.1.5 on 2019-01-27 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('announcement', '0007_custom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customcat',
            fields=[
                ('u', models.ForeignKey(db_column='U_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customcat',
                'managed': False,
            },
        ),
    ]
